# src/utils.py
import os
import glob
import IPython.display as ipd
import matplotlib.pyplot as plt
import librosa.display
import librosa
import numpy as np

def play_latest_generated_samples(output_dir, n=3):
    """
    Finds the latest test audios generated by the Trainer and plays them.
    """
    search_pattern = os.path.join(output_dir, "**", "*.wav")
    wav_files = glob.glob(search_pattern, recursive=True)
    
    if not wav_files:
        print("No audio samples found yet. Wait for the first evaluation step.")
        return

    wav_files.sort(key=os.path.getmtime, reverse=True)
    
    print(f"Playing top {n} latest generated samples:")
    
    for wav_path in wav_files[:n]:
        filename = os.path.basename(wav_path)
        print(f"--- {filename} ---")
        ipd.display(ipd.Audio(wav_path))

def plot_loss_logs(output_dir):
    """
    Parses the trainer logs (if available as JSON/CSV) or relies on Tensorboard.
    For a quick notebook check, we just remind the user to check Tensorboard.
    """
    print(f"To see live metrics, run this in a terminal:\n tensorboard --logdir {output_dir}")